### PR TITLE
Move distribution to Moo

### PR DESCRIPTION
**Pull request by jjatria**
Not sure what you'll think about this patch, but loading Moose for what this library needs seems excessive.

It will make adoption on CPAN easier (certainly for me!).

### CODE REVIEW

**Comment by yanick** [comment]
I'm usually the other way around: if I don't  have a specific need for speed, I go for the Moo* with the biggest box of toys. :-)  But fair, there is no immediate need for it and you went through the work to Moo it back, so I'll take it. :-)

**Comment by yanick** [comment]
@jjatria There are still modules in the distro using Moose. Could you sweep them all to Moo?

**Comment by jjatria** [comment]
Oops! Yeah, I completely missed all those other classes.

I've moved them all to Moo, and removed the explicit `use strict` and `use warnings`, since those are already loaded by Moo (although I could understand you wanting them on explicitly).

Where I did this, I also moved the Moo import to the top, to where the strictures and warnings were originally enabled.

The change ended up being larger than I anticipated, so if I did anything you didn't like, just let me know. And thank you for being so responsive!

**Comment by yanick** [comment]
> I've moved them all to Moo, and removed the explicit use strict and use warnings, since those are already loaded by Moo (although I could understand you wanting them on explicitly).

Yeah, I know Moo and Moose turn stricture explicitly, but I have the habit of putting those lines explicitly because although I agree those lines should be there, I don't like that Moo/Moose do it for me, as I don't think it's their job to do that. It's kind of having the waiter at the restaurant picking my fork and knife and cutting my steak into small pieces. :-)

But it's not bothering me enough to change your PR. I'll let Moo cut my steak for the time being. ;-)

**Comment by yanick** [comment]
Merged! Should be pushed to CPAN over lunch. Thanks!

**Comment by jjatria** [comment]
> I have the habit of putting those lines explicitly because [...] I don't think it's their job to do that

I thought that might be the case. My bad! I'll keep them around next time I touch your code

**Comment by yanick** [comment]
> I thought that might be the case. My bad! I'll keep them around next time I touch your code

Don't worry about it. No foul done. It's just a personal preference, and nothing worth raising hell for. :-)

**Pull request closed without merging**
